<a href="https://colab.research.google.com/github/Harshitranjan07/Data-science/blob/main/Lec05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
weekly_sales = {}

while True:
    item = input().strip().lower()

    if item == "end":
        break

    quantity = int(input(f"How many {item}s were sold?: "))

    if item in weekly_sales:
        weekly_sales[item] += quantity
    else:
        weekly_sales[item] = quantity
    print(f"Recorded: +{quantity} {item}(s)\n")

    for item, total_sold in weekly_sales.items():
        print(f"• {item.capitalize()}: {total_sold} sold")

In [ ]:
import numpy as np

matrix = [[np.random.randint(1, 90) for _ in range(5)] for _ in range(5)]

for row in matrix:
      print(row)

row_means = np.mean(matrix, axis=1)
print("Row-wise means:", row_means)


modified_matrix = [[-1 if x % 2 == 0 else x for x in row] for row in matrix]

print("Matrix with even numbers replaced by -1:")
for row in modified_matrix:
    print(row)








In [16]:
import numpy as np

mat = np.random.randint(1, 91, size=(5, 5))
print("matrix :" , mat)

row_wise_means = np.mean(mat, axis=1)
column_wise_means = np.mean(mat, axis=0)

print("Row-wise means:", row_wise_means)
print("Column-wise means:", column_wise_means)

modified_matrix = np.where(mat % 2 == 0, -1, mat)
print("Matrix with even numbers replaced by -1:")
print(modified_matrix)

sorted_row = np.sort(mat, axis=1)
sorted_column = np.sort(mat, axis=0)

print("Row-wise sorted matrix:")
print(sorted_row)
print("Column-wise sorted matrix:")
print(sorted_column)

rowiwse_sum = np.sum(mat, axis=1)
column_wise_sum = np.sum(mat, axis=0)

print("Row-wise sum:", rowiwse_sum)
print("Column-wise sum:", column_wise_sum)

count_col = np.sum(np.where(mat < 0, 1, 0), axis=0)
print(count_col)

matrix : [[21 76 79 12 83]
 [37 48 25 49 81]
 [89 63 76 16 90]
 [43 57  7  4 49]
 [12 52 41 75 40]]
Row-wise means: [54.2 48.  66.8 32.  44. ]
Column-wise means: [40.4 59.2 45.6 31.2 68.6]
Matrix with even numbers replaced by -1:
[[21 -1 79 -1 83]
 [37 -1 25 49 81]
 [89 63 -1 -1 -1]
 [43 57  7 -1 49]
 [-1 -1 41 75 -1]]
Row-wise sorted matrix:
[[12 21 76 79 83]
 [25 37 48 49 81]
 [16 63 76 89 90]
 [ 4  7 43 49 57]
 [12 40 41 52 75]]
Column-wise sorted matrix:
[[12 48  7  4 40]
 [21 52 25 12 49]
 [37 57 41 16 81]
 [43 63 76 49 83]
 [89 76 79 75 90]]
Row-wise sum: [271 240 334 160 220]
Column-wise sum: [202 296 228 156 343]
[0 0 0 0 0]


In [17]:
# Question 2

# Inventry control system

#Task


# create a 5*5 array(stock level)

mat1 = np.random.randint(20,90, size=(5, 5))
print("matrix :" , mat1)

# create another 5*5 array (demand)
mat2 = np.random.randint(20,90, size=(5, 5))
print("matrix :" , mat2)

# releasing stock  = stock - demand

mat = mat1 - mat2
print("matrix :" , mat)

#neagative values = 0 (out of stock)

mat = np.random.randint (0,90, size=(5, 5))
print("matrix :" , mat)


#total shortage
total_shortage = np.sum(mat)
print("total shortage :" , total_shortage)

#product with zero stock

product_zero_stock = np.where(mat == 0)
print("product with zero stock :" , product_zero_stock)


#sort each row based on remaining stock

sort_remaining_stock = np.sort(mat, axis=1)
print("sort each row based on remaining stock :" , sort_remaining_stock)


matrix : [[59 28 29 69 54]
 [59 50 78 56 30]
 [24 78 68 85 37]
 [88 20 36 60 58]
 [86 71 56 72 32]]
matrix : [[70 26 70 79 73]
 [28 44 74 52 29]
 [74 83 72 79 28]
 [29 54 72 67 55]
 [47 23 38 83 25]]
matrix : [[-11   2 -41 -10 -19]
 [ 31   6   4   4   1]
 [-50  -5  -4   6   9]
 [ 59 -34 -36  -7   3]
 [ 39  48  18 -11   7]]
matrix : [[12 62 28 61  2]
 [84 48 80 80 28]
 [33 44 45 57  3]
 [86 62 69  9 31]
 [69 56 11 36 54]]
total shortage : 1150
product with zero stock : (array([], dtype=int64), array([], dtype=int64))
sort each row based on remaining stock : [[ 2 12 28 61 62]
 [28 48 80 80 84]
 [ 3 33 44 45 57]
 [ 9 31 62 69 86]
 [11 36 54 56 69]]


In [21]:
import pandas as pd

df = pd.read_csv("/content/student_data.csv")
print(df)

      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7   
1               4          69            5               3   
2              11          60            7               6   
3               8          99            9               8   
4               5          52            8               6   
...           ...         ...          ...             ...   
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
0                        10              62      100.00           Placed  
1                         8              56      100.00           Placed  
2                        10   