<a href="https://colab.research.google.com/github/Harshitranjan07/Data-science/blob/main/NumpyLec04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import numpy as np
np_array = np.array([1,3,9,0,'hello',False])
print(bool(np_array[-1]))

b= False
print(bool(b))

True
False


In [ ]:
a='0'
print(bool(a))

True


In [ ]:
a= np.zeros([2,3,4])
print(a)
print(type(a[0][0][0]))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<class 'numpy.float64'>


In [ ]:
a=np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [ ]:
a= np.arange(5,10)
print(a)

[5 6 7 8 9]


In [ ]:
a=np.linspace(3,12,4,dtype=int)
print(a)

[ 3  6  9 12]


In [ ]:
a = np.array([2,3], dtype=int)
print(a.shape,a.size)
# np.size(a)

(2,) 2


In [ ]:
a = np.random.randint(1,7,4)
print(a)

b = np.random.choice([2,4,2,9],2)
print(b)

[2 1 3 5]
[2 4]


In [58]:
a = np.array([2,6,8,7])
b = np.array([3,9,10,8])
print(a*2)
print(a+b)
print(a*b)

[ 4 12 16 14]
[ 5 15 18 15]
[ 6 54 80 56]


In [63]:
a = np.random.randint(2,15,6)
print(a)

b = a.reshape([3,2])
print(b)

[13  9  4  8 13 12]
[[13  9]
 [ 4  8]
 [13 12]]


In [65]:
a = np.array([2,3,5,7])
b = np.array([3,6,8,2])

concat = np.concatenate((a,b))
print(concat)

trans = np .transpose((a,b))
print(trans)

[2 3 5 7 3 6 8 2]
[[2 3]
 [3 6]
 [5 8]
 [7 2]]


In [69]:
a = np.random.randint(2,15,6)
b = np.random.randint(1,19,6)

print(a)
print(b)

c = np.where(b>2,b,a)
print(c)

[10  2  5 10 13  2]
[15  1  6  2  3 10]
[15  2  6 10  3 10]


In [76]:
lst = []
for i in range(7):
  print("day",i,":")
  lst.append(int(input()))

a=np.array(lst)
print(a)

print("min",np.min(a))
print("max",np.max(a))
print("mean",np.mean(a))
print("median",np.median(a))
print("std",np.std(a))

day 0 :
50
day 1 :
20
day 2 :
40
day 3 :
60
day 4 :
50
day 5 :
80
day 6 :
90
[50 20 40 60 50 80 90]
min 20
max 90
mean 55.714285714285715
median 50.0
std 21.946130708196023
